apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: muhammadahsankamalpipelinesjavascriptdocker2 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: muhammadahsankamalpipelinesjavascriptdocker2 
    spec:
      containers:
        - name: muhammadahsankamalpipelinesjavascriptdocker2 
          image: mycreg.azurecr.io/muhammadahsankamalpipelinesjavascriptdocker2
          ports:
          - containerPort: 8080