apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: muhammadahsankamalpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: muhammadahsankamalpipelinesjavascriptdocker 
    spec:
      containers:
        - name: muhammadahsankamalpipelinesjavascriptdocker 
          image: mycreg.azurecr.io/muhammadahsankamalpipelinesjavascriptdocker
          ports:
          - containerPort: 8081